build-dev-back:
  extends:
    - .build
    - .for_dev
  variables:
    BUILD_TARGET: back
    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}

build-dev-front:
  extends:
    - .build
    - .for_dev
  variables:
    BUILD_TARGET: front
    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}

build-prod-back:
  extends:
    - .build
    - .for_prod
  variables:
    BUILD_TARGET: back

build-prod-front:
  extends:
    - .build
    - .for_prod
  variables:
    BUILD_TARGET: front
