version: "3"
services:
  front:
    image: ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_TAG}
    ports:
      - 127.0.0.1:8080:8080
    network_mode: "host"
  back:
    image: ${CI_REGISTRY_IMAGE}/back:${CI_COMMIT_TAG}
    ports:
      - 127.0.0.1:81:80
    network_mode: "host"
  proxy:
    image: bitnami/nginx:1.25.1-debian-11-r2
    ports:
      - 80:80
      - 443:443
    volumes:
      - tls:/tmp/tls
      - proxy-config.conf:/opt/bitnami/nginx/conf/server_blocks/proxy-config.conf
    network_mode: "host"